// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package unittest.proxies;

public class Company
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject companyMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UnitTest.Company";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Company("Company"),
		Phone("Phone"),
		GeneralEmail("GeneralEmail"),
		CEOName("CEOName"),
		CEOEmail("CEOEmail"),
		Website("Website"),
		Address("Address"),
		City("City"),
		State("State"),
		Zipcode("Zipcode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Company(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "UnitTest.Company"));
	}

	protected Company(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject companyMendixObject)
	{
		if (companyMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("UnitTest.Company", companyMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a UnitTest.Company");

		this.companyMendixObject = companyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Company.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static unittest.proxies.Company initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return unittest.proxies.Company.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static unittest.proxies.Company initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new unittest.proxies.Company(context, mendixObject);
	}

	public static unittest.proxies.Company load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return unittest.proxies.Company.initialize(context, mendixObject);
	}

	public static java.util.List<unittest.proxies.Company> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<unittest.proxies.Company> result = new java.util.ArrayList<unittest.proxies.Company>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//UnitTest.Company" + xpathConstraint))
			result.add(unittest.proxies.Company.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Company
	 */
	public final String getCompany()
	{
		return getCompany(getContext());
	}

	/**
	 * @param context
	 * @return value of Company
	 */
	public final String getCompany(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Company.toString());
	}

	/**
	 * Set value of Company
	 * @param company
	 */
	public final void setCompany(String company)
	{
		setCompany(getContext(), company);
	}

	/**
	 * Set value of Company
	 * @param context
	 * @param company
	 */
	public final void setCompany(com.mendix.systemwideinterfaces.core.IContext context, String company)
	{
		getMendixObject().setValue(context, MemberNames.Company.toString(), company);
	}

	/**
	 * @return value of Phone
	 */
	public final String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * @return value of GeneralEmail
	 */
	public final String getGeneralEmail()
	{
		return getGeneralEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of GeneralEmail
	 */
	public final String getGeneralEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.GeneralEmail.toString());
	}

	/**
	 * Set value of GeneralEmail
	 * @param generalemail
	 */
	public final void setGeneralEmail(String generalemail)
	{
		setGeneralEmail(getContext(), generalemail);
	}

	/**
	 * Set value of GeneralEmail
	 * @param context
	 * @param generalemail
	 */
	public final void setGeneralEmail(com.mendix.systemwideinterfaces.core.IContext context, String generalemail)
	{
		getMendixObject().setValue(context, MemberNames.GeneralEmail.toString(), generalemail);
	}

	/**
	 * @return value of CEOName
	 */
	public final String getCEOName()
	{
		return getCEOName(getContext());
	}

	/**
	 * @param context
	 * @return value of CEOName
	 */
	public final String getCEOName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.CEOName.toString());
	}

	/**
	 * Set value of CEOName
	 * @param ceoname
	 */
	public final void setCEOName(String ceoname)
	{
		setCEOName(getContext(), ceoname);
	}

	/**
	 * Set value of CEOName
	 * @param context
	 * @param ceoname
	 */
	public final void setCEOName(com.mendix.systemwideinterfaces.core.IContext context, String ceoname)
	{
		getMendixObject().setValue(context, MemberNames.CEOName.toString(), ceoname);
	}

	/**
	 * @return value of CEOEmail
	 */
	public final String getCEOEmail()
	{
		return getCEOEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of CEOEmail
	 */
	public final String getCEOEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.CEOEmail.toString());
	}

	/**
	 * Set value of CEOEmail
	 * @param ceoemail
	 */
	public final void setCEOEmail(String ceoemail)
	{
		setCEOEmail(getContext(), ceoemail);
	}

	/**
	 * Set value of CEOEmail
	 * @param context
	 * @param ceoemail
	 */
	public final void setCEOEmail(com.mendix.systemwideinterfaces.core.IContext context, String ceoemail)
	{
		getMendixObject().setValue(context, MemberNames.CEOEmail.toString(), ceoemail);
	}

	/**
	 * @return value of Website
	 */
	public final String getWebsite()
	{
		return getWebsite(getContext());
	}

	/**
	 * @param context
	 * @return value of Website
	 */
	public final String getWebsite(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Website.toString());
	}

	/**
	 * Set value of Website
	 * @param website
	 */
	public final void setWebsite(String website)
	{
		setWebsite(getContext(), website);
	}

	/**
	 * Set value of Website
	 * @param context
	 * @param website
	 */
	public final void setWebsite(com.mendix.systemwideinterfaces.core.IContext context, String website)
	{
		getMendixObject().setValue(context, MemberNames.Website.toString(), website);
	}

	/**
	 * @return value of Address
	 */
	public final String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of City
	 */
	public final String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of State
	 */
	public final String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of Zipcode
	 */
	public final String getZipcode()
	{
		return getZipcode(getContext());
	}

	/**
	 * @param context
	 * @return value of Zipcode
	 */
	public final String getZipcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Zipcode.toString());
	}

	/**
	 * Set value of Zipcode
	 * @param zipcode
	 */
	public final void setZipcode(String zipcode)
	{
		setZipcode(getContext(), zipcode);
	}

	/**
	 * Set value of Zipcode
	 * @param context
	 * @param zipcode
	 */
	public final void setZipcode(com.mendix.systemwideinterfaces.core.IContext context, String zipcode)
	{
		getMendixObject().setValue(context, MemberNames.Zipcode.toString(), zipcode);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return companyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final unittest.proxies.Company that = (unittest.proxies.Company) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "UnitTest.Company";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
