// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package unittest.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the UnitTest module

	public static Long getCompaniesIndex()
	{
		return (Long)Core.getConfiguration().getConstantValue("UnitTest.CompaniesIndex");
	}

	public static Long getCustomersIndex()
	{
		return (Long)Core.getConfiguration().getConstantValue("UnitTest.CustomersIndex");
	}

	public static Long getDocumentIndex()
	{
		return (Long)Core.getConfiguration().getConstantValue("UnitTest.DocumentIndex");
	}

	public static String getLognode()
	{
		return (String)Core.getConfiguration().getConstantValue("UnitTest.Lognode");
	}
}