// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package lucene.proxies;

public enum IndexType
{
	Documents(new String[][] { new String[] { "en_US", "Documents" }, new String[] { "nl_NL", "Documenten" } }),
	Customers(new String[][] { new String[] { "en_US", "Customers" }, new String[] { "nl_NL", "Klanten" } });

	private java.util.Map<String,String> captions;

	private IndexType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
