// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package lucene.proxies;

/**
 * Connect this with all indexed entities
 */
public class SearchResult
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searchResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Lucene.SearchResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MxType("MxType"),
		MxId("MxId"),
		SearchResult_SampleFileDocument("Lucene.SearchResult_SampleFileDocument"),
		SearchResult_SampleCustomer("Lucene.SearchResult_SampleCustomer"),
		SearchResult_Customer("Lucene.SearchResult_Customer"),
		SearchResult_Report("Lucene.SearchResult_Report"),
		SearchResult_Company("Lucene.SearchResult_Company");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SearchResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Lucene.SearchResult"));
	}

	protected SearchResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchResultMendixObject)
	{
		if (searchResultMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Lucene.SearchResult", searchResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Lucene.SearchResult");

		this.searchResultMendixObject = searchResultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SearchResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static lucene.proxies.SearchResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return lucene.proxies.SearchResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static lucene.proxies.SearchResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new lucene.proxies.SearchResult(context, mendixObject);
	}

	public static lucene.proxies.SearchResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return lucene.proxies.SearchResult.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MxType
	 */
	public final String getMxType()
	{
		return getMxType(getContext());
	}

	/**
	 * @param context
	 * @return value of MxType
	 */
	public final String getMxType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.MxType.toString());
	}

	/**
	 * Set value of MxType
	 * @param mxtype
	 */
	public final void setMxType(String mxtype)
	{
		setMxType(getContext(), mxtype);
	}

	/**
	 * Set value of MxType
	 * @param context
	 * @param mxtype
	 */
	public final void setMxType(com.mendix.systemwideinterfaces.core.IContext context, String mxtype)
	{
		getMendixObject().setValue(context, MemberNames.MxType.toString(), mxtype);
	}

	/**
	 * @return value of MxId
	 */
	public final String getMxId()
	{
		return getMxId(getContext());
	}

	/**
	 * @param context
	 * @return value of MxId
	 */
	public final String getMxId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.MxId.toString());
	}

	/**
	 * Set value of MxId
	 * @param mxid
	 */
	public final void setMxId(String mxid)
	{
		setMxId(getContext(), mxid);
	}

	/**
	 * Set value of MxId
	 * @param context
	 * @param mxid
	 */
	public final void setMxId(com.mendix.systemwideinterfaces.core.IContext context, String mxid)
	{
		getMendixObject().setValue(context, MemberNames.MxId.toString(), mxid);
	}

	/**
	 * @return value of SearchResult_SampleFileDocument
	 */
	public final lucene.proxies.SampleFileDocument getSearchResult_SampleFileDocument() throws com.mendix.core.CoreException
	{
		return getSearchResult_SampleFileDocument(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchResult_SampleFileDocument
	 */
	public final lucene.proxies.SampleFileDocument getSearchResult_SampleFileDocument(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		lucene.proxies.SampleFileDocument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SearchResult_SampleFileDocument.toString());
		if (identifier != null)
			result = lucene.proxies.SampleFileDocument.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SearchResult_SampleFileDocument
	 * @param searchresult_samplefiledocument
	 */
	public final void setSearchResult_SampleFileDocument(lucene.proxies.SampleFileDocument searchresult_samplefiledocument)
	{
		setSearchResult_SampleFileDocument(getContext(), searchresult_samplefiledocument);
	}

	/**
	 * Set value of SearchResult_SampleFileDocument
	 * @param context
	 * @param searchresult_samplefiledocument
	 */
	public final void setSearchResult_SampleFileDocument(com.mendix.systemwideinterfaces.core.IContext context, lucene.proxies.SampleFileDocument searchresult_samplefiledocument)
	{
		if (searchresult_samplefiledocument == null)
			getMendixObject().setValue(context, MemberNames.SearchResult_SampleFileDocument.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SearchResult_SampleFileDocument.toString(), searchresult_samplefiledocument.getMendixObject().getId());
	}

	/**
	 * @return value of SearchResult_SampleCustomer
	 */
	public final lucene.proxies.SampleCustomer getSearchResult_SampleCustomer() throws com.mendix.core.CoreException
	{
		return getSearchResult_SampleCustomer(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchResult_SampleCustomer
	 */
	public final lucene.proxies.SampleCustomer getSearchResult_SampleCustomer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		lucene.proxies.SampleCustomer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SearchResult_SampleCustomer.toString());
		if (identifier != null)
			result = lucene.proxies.SampleCustomer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SearchResult_SampleCustomer
	 * @param searchresult_samplecustomer
	 */
	public final void setSearchResult_SampleCustomer(lucene.proxies.SampleCustomer searchresult_samplecustomer)
	{
		setSearchResult_SampleCustomer(getContext(), searchresult_samplecustomer);
	}

	/**
	 * Set value of SearchResult_SampleCustomer
	 * @param context
	 * @param searchresult_samplecustomer
	 */
	public final void setSearchResult_SampleCustomer(com.mendix.systemwideinterfaces.core.IContext context, lucene.proxies.SampleCustomer searchresult_samplecustomer)
	{
		if (searchresult_samplecustomer == null)
			getMendixObject().setValue(context, MemberNames.SearchResult_SampleCustomer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SearchResult_SampleCustomer.toString(), searchresult_samplecustomer.getMendixObject().getId());
	}

	/**
	 * @return value of SearchResult_Customer
	 */
	public final unittest.proxies.Customer getSearchResult_Customer() throws com.mendix.core.CoreException
	{
		return getSearchResult_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchResult_Customer
	 */
	public final unittest.proxies.Customer getSearchResult_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		unittest.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SearchResult_Customer.toString());
		if (identifier != null)
			result = unittest.proxies.Customer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SearchResult_Customer
	 * @param searchresult_customer
	 */
	public final void setSearchResult_Customer(unittest.proxies.Customer searchresult_customer)
	{
		setSearchResult_Customer(getContext(), searchresult_customer);
	}

	/**
	 * Set value of SearchResult_Customer
	 * @param context
	 * @param searchresult_customer
	 */
	public final void setSearchResult_Customer(com.mendix.systemwideinterfaces.core.IContext context, unittest.proxies.Customer searchresult_customer)
	{
		if (searchresult_customer == null)
			getMendixObject().setValue(context, MemberNames.SearchResult_Customer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SearchResult_Customer.toString(), searchresult_customer.getMendixObject().getId());
	}

	/**
	 * @return value of SearchResult_Report
	 */
	public final unittest.proxies.Report getSearchResult_Report() throws com.mendix.core.CoreException
	{
		return getSearchResult_Report(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchResult_Report
	 */
	public final unittest.proxies.Report getSearchResult_Report(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		unittest.proxies.Report result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SearchResult_Report.toString());
		if (identifier != null)
			result = unittest.proxies.Report.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SearchResult_Report
	 * @param searchresult_report
	 */
	public final void setSearchResult_Report(unittest.proxies.Report searchresult_report)
	{
		setSearchResult_Report(getContext(), searchresult_report);
	}

	/**
	 * Set value of SearchResult_Report
	 * @param context
	 * @param searchresult_report
	 */
	public final void setSearchResult_Report(com.mendix.systemwideinterfaces.core.IContext context, unittest.proxies.Report searchresult_report)
	{
		if (searchresult_report == null)
			getMendixObject().setValue(context, MemberNames.SearchResult_Report.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SearchResult_Report.toString(), searchresult_report.getMendixObject().getId());
	}

	/**
	 * @return value of SearchResult_Company
	 */
	public final unittest.proxies.Company getSearchResult_Company() throws com.mendix.core.CoreException
	{
		return getSearchResult_Company(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchResult_Company
	 */
	public final unittest.proxies.Company getSearchResult_Company(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		unittest.proxies.Company result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SearchResult_Company.toString());
		if (identifier != null)
			result = unittest.proxies.Company.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SearchResult_Company
	 * @param searchresult_company
	 */
	public final void setSearchResult_Company(unittest.proxies.Company searchresult_company)
	{
		setSearchResult_Company(getContext(), searchresult_company);
	}

	/**
	 * Set value of SearchResult_Company
	 * @param context
	 * @param searchresult_company
	 */
	public final void setSearchResult_Company(com.mendix.systemwideinterfaces.core.IContext context, unittest.proxies.Company searchresult_company)
	{
		if (searchresult_company == null)
			getMendixObject().setValue(context, MemberNames.SearchResult_Company.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SearchResult_Company.toString(), searchresult_company.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searchResultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final lucene.proxies.SearchResult that = (lucene.proxies.SearchResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Lucene.SearchResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
