// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package lucene.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the Lucene module
	public static boolean aSu_RestoreBackup(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			return (Boolean)Core.execute(context, "Lucene.ASu_RestoreBackup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bCo_SampleCustomer(IContext context, lucene.proxies.SampleCustomer _sampleCustomer)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("SampleCustomer", _sampleCustomer == null ? null : _sampleCustomer.getMendixObject());
			return (Boolean)Core.execute(context, "Lucene.BCo_SampleCustomer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean bDe_SampleCustomer(IContext context, lucene.proxies.SampleCustomer _sampleCustomer)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("SampleCustomer", _sampleCustomer == null ? null : _sampleCustomer.getMendixObject());
			return (Boolean)Core.execute(context, "Lucene.BDe_SampleCustomer", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void bSd_CreateBackup(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "Lucene.BSd_CreateBackup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void createBackup(IContext context, Long _indexId)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("indexId", _indexId);
			Core.execute(context, "Lucene.CreateBackup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_CreateLuceneBackup_Step1(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "Lucene.MB_CreateLuceneBackup_Step1", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_CreateLuceneBackup_Step2(IContext context, lucene.proxies.LuceneBackup _luceneBackup)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("LuceneBackup", _luceneBackup == null ? null : _luceneBackup.getMendixObject());
			Core.execute(context, "Lucene.MB_CreateLuceneBackup_Step2", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_CreateNightlyBackup(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "Lucene.MB_CreateNightlyBackup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_DeleteIndex(IContext context, lucene.proxies.SearchCommand _searchCommand)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("SearchCommand", _searchCommand == null ? null : _searchCommand.getMendixObject());
			Core.execute(context, "Lucene.MB_DeleteIndex", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_IndexSize(IContext context, lucene.proxies.SearchCommand _searchCommand)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("SearchCommand", _searchCommand == null ? null : _searchCommand.getMendixObject());
			Core.execute(context, "Lucene.MB_IndexSize", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_OpenSearchResult(IContext context, lucene.proxies.SearchResult _searchResult)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("SearchResult", _searchResult == null ? null : _searchResult.getMendixObject());
			Core.execute(context, "Lucene.MB_OpenSearchResult", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_RestoreBackup(IContext context, lucene.proxies.LuceneBackup _luceneBackup)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("LuceneBackup", _luceneBackup == null ? null : _luceneBackup.getMendixObject());
			Core.execute(context, "Lucene.MB_RestoreBackup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_Search(IContext context, lucene.proxies.SearchCommand _search)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Search", _search == null ? null : _search.getMendixObject());
			Core.execute(context, "Lucene.MB_Search", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void mB_StartSearch(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "Lucene.MB_StartSearch", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_IndexType(IContext context, lucene.proxies.LuceneBackup _luceneBackup)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("LuceneBackup", _luceneBackup == null ? null : _luceneBackup.getMendixObject());
			Core.execute(context, "Lucene.OCh_IndexType", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oCh_SearchIndexType(IContext context, lucene.proxies.SearchCommand _luceneBackup)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("LuceneBackup", _luceneBackup == null ? null : _luceneBackup.getMendixObject());
			Core.execute(context, "Lucene.OCh_SearchIndexType", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void restoreLastBackup(IContext context, Long _indexId)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("IndexId", _indexId);
			Core.execute(context, "Lucene.RestoreLastBackup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}