// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package lucene.actions;

import org.apache.lucene.document.Document;
import org.apache.lucene.document.Field;
import org.apache.lucene.document.TextField;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import lucene.helpers.LuceneFactory;

/**
 * Delete an object from the index. Processing may take some time. (< 5 seconds)
 */
public class DeleteFromIndex extends CustomJavaAction<Boolean>
{
	private Long indexId;
	private IMendixObject anyObject;

	public DeleteFromIndex(IContext context, Long indexId, IMendixObject anyObject)
	{
		super(context);
		this.indexId = indexId;
		this.anyObject = anyObject;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		// helper doc is only used to pass the mxid
		Document doc = new Document();
		doc.add(new TextField(LuceneFactory.MXID, Long.toString(anyObject.getId().toLong()), Field.Store.YES));
		LuceneFactory.getInstance().deleteDocumentQueued(indexId, doc);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "DeleteFromIndex";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
