// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package lucene.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * replace escape special lucene characters.
 * + - ! ( ) { } [ ] ^ " ~ * ? : \ /
 * 
 * for example /4416 with \/4416 to make lucene find the literal value.
 */
public class EscapeCharacters extends CustomJavaAction<String>
{
	private String searchTerm;

	public EscapeCharacters(IContext context, String searchTerm)
	{
		super(context);
		this.searchTerm = searchTerm;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
		// escape all special lucene characters.
		// + - && || ! ( ) { } [ ] ^ " ~ * ? : \ /
		String s = null;
		if (searchTerm != null) {
			s = "";
			String escaped = "+-!(){}[]^\"~*?:\\/";
			for (int i = 0; i < searchTerm.length(); i++) {
				String c = searchTerm.substring(i, i+1);
				if (escaped.contains(c)) {
					s = s + "\\";
				}
				s = s + c;
			}
		}
		return s;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "EscapeCharacters";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
