// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package lucene.actions;

import java.io.IOException;
import java.io.StringReader;
import org.apache.lucene.analysis.charfilter.HTMLStripCharFilter;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Extract the text from HTML attributes like used in Rich Text Editors.
 */
public class ExtractTextFromHTML extends CustomJavaAction<String>
{
	private String html;

	public ExtractTextFromHTML(IContext context, String html)
	{
		super(context);
		this.html = html;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder out = new StringBuilder();
		StringReader strReader = new StringReader(html);
		try {
			HTMLStripCharFilter html = new HTMLStripCharFilter(strReader);
			char[] cbuf = new char[1024 * 10];
			while (true) {
				int count = html.read(cbuf);
				if (count == -1)
					break; // end of stream mark is -1
				if (count > 0)
					out.append(cbuf, 0, count);
			}
			html.close();
		} catch (IOException e) {
			//todo
		}
		return out.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "ExtractTextFromHTML";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
