// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package lucene.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import lucene.helpers.LuceneFactory;

public class WaitUntilIndexingReady extends CustomJavaAction<Boolean>
{
	private Long indexId;

	public WaitUntilIndexingReady(IContext context, Long indexId)
	{
		super(context);
		this.indexId = indexId;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return LuceneFactory.getInstance().indexingReady(indexId);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "WaitUntilIndexingReady";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
